
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const calendar_type = {
  Hari_Libur: 'Hari_Libur',
  Cuti_Bersama: 'Cuti_Bersama',
  Event_Kantor: 'Event_Kantor'
} as const

export type calendar_type = (typeof calendar_type)[keyof typeof calendar_type]


export const dept_status = {
  Aktif: 'Aktif',
  Nonaktif: 'Nonaktif'
} as const

export type dept_status = (typeof dept_status)[keyof typeof dept_status]


export const skpd_status = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE'
} as const

export type skpd_status = (typeof skpd_status)[keyof typeof skpd_status]


export const ijin_status = {
  Waiting: 'Waiting',
  Reject: 'Reject',
  Approved: 'Approved',
  Cancelled: 'Cancelled'
} as const

export type ijin_status = (typeof ijin_status)[keyof typeof ijin_status]


export const cuti_status = {
  Waiting: 'Waiting',
  Reject: 'Reject',
  Approved: 'Approved',
  Cancelled: 'Cancelled'
} as const

export type cuti_status = (typeof cuti_status)[keyof typeof cuti_status]


export const srl_status1 = {
  Waiting: 'Waiting',
  Reject: 'Reject',
  Approved: 'Approved',
  Cancelled: 'Cancelled'
} as const

export type srl_status1 = (typeof srl_status1)[keyof typeof srl_status1]


export const srl_status2 = {
  Waiting: 'Waiting',
  Reject: 'Reject',
  Approved: 'Approved',
  Cancelled: 'Cancelled'
} as const

export type srl_status2 = (typeof srl_status2)[keyof typeof srl_status2]


export const spl_status1 = {
  Waiting: 'Waiting',
  Reject: 'Reject',
  Approved: 'Approved',
  Cancelled: 'Cancelled'
} as const

export type spl_status1 = (typeof spl_status1)[keyof typeof spl_status1]


export const spl_status2 = {
  Waiting: 'Waiting',
  Reject: 'Reject',
  Approved: 'Approved',
  Cancelled: 'Cancelled'
} as const

export type spl_status2 = (typeof spl_status2)[keyof typeof spl_status2]


export const employee_status = {
  Aktif: 'Aktif',
  Nonaktif: 'Nonaktif'
} as const

export type employee_status = (typeof employee_status)[keyof typeof employee_status]


export const profile_status = {
  Aktif: 'Aktif',
  Nonaktif: 'Nonaktif'
} as const

export type profile_status = (typeof profile_status)[keyof typeof profile_status]
