
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `sppd_detail` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model sppd_detail
 * 
 */
export type sppd_detailModel = runtime.Types.Result.DefaultSelection<Prisma.$sppd_detailPayload>

export type AggregateSppd_detail = {
  _count: Sppd_detailCountAggregateOutputType | null
  _avg: Sppd_detailAvgAggregateOutputType | null
  _sum: Sppd_detailSumAggregateOutputType | null
  _min: Sppd_detailMinAggregateOutputType | null
  _max: Sppd_detailMaxAggregateOutputType | null
}

export type Sppd_detailAvgAggregateOutputType = {
  step: number | null
}

export type Sppd_detailSumAggregateOutputType = {
  step: number | null
}

export type Sppd_detailMinAggregateOutputType = {
  sppd_detail_id: string | null
  step: number | null
  sppd_id: string | null
  payroll: string | null
  description: string | null
}

export type Sppd_detailMaxAggregateOutputType = {
  sppd_detail_id: string | null
  step: number | null
  sppd_id: string | null
  payroll: string | null
  description: string | null
}

export type Sppd_detailCountAggregateOutputType = {
  sppd_detail_id: number
  step: number
  sppd_id: number
  payroll: number
  description: number
  _all: number
}


export type Sppd_detailAvgAggregateInputType = {
  step?: true
}

export type Sppd_detailSumAggregateInputType = {
  step?: true
}

export type Sppd_detailMinAggregateInputType = {
  sppd_detail_id?: true
  step?: true
  sppd_id?: true
  payroll?: true
  description?: true
}

export type Sppd_detailMaxAggregateInputType = {
  sppd_detail_id?: true
  step?: true
  sppd_id?: true
  payroll?: true
  description?: true
}

export type Sppd_detailCountAggregateInputType = {
  sppd_detail_id?: true
  step?: true
  sppd_id?: true
  payroll?: true
  description?: true
  _all?: true
}

export type Sppd_detailAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which sppd_detail to aggregate.
   */
  where?: Prisma.sppd_detailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sppd_details to fetch.
   */
  orderBy?: Prisma.sppd_detailOrderByWithRelationInput | Prisma.sppd_detailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.sppd_detailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sppd_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sppd_details.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned sppd_details
  **/
  _count?: true | Sppd_detailCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Sppd_detailAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Sppd_detailSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Sppd_detailMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Sppd_detailMaxAggregateInputType
}

export type GetSppd_detailAggregateType<T extends Sppd_detailAggregateArgs> = {
      [P in keyof T & keyof AggregateSppd_detail]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSppd_detail[P]>
    : Prisma.GetScalarType<T[P], AggregateSppd_detail[P]>
}




export type sppd_detailGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.sppd_detailWhereInput
  orderBy?: Prisma.sppd_detailOrderByWithAggregationInput | Prisma.sppd_detailOrderByWithAggregationInput[]
  by: Prisma.Sppd_detailScalarFieldEnum[] | Prisma.Sppd_detailScalarFieldEnum
  having?: Prisma.sppd_detailScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Sppd_detailCountAggregateInputType | true
  _avg?: Sppd_detailAvgAggregateInputType
  _sum?: Sppd_detailSumAggregateInputType
  _min?: Sppd_detailMinAggregateInputType
  _max?: Sppd_detailMaxAggregateInputType
}

export type Sppd_detailGroupByOutputType = {
  sppd_detail_id: string
  step: number
  sppd_id: string | null
  payroll: string | null
  description: string
  _count: Sppd_detailCountAggregateOutputType | null
  _avg: Sppd_detailAvgAggregateOutputType | null
  _sum: Sppd_detailSumAggregateOutputType | null
  _min: Sppd_detailMinAggregateOutputType | null
  _max: Sppd_detailMaxAggregateOutputType | null
}

type GetSppd_detailGroupByPayload<T extends sppd_detailGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Sppd_detailGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Sppd_detailGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Sppd_detailGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Sppd_detailGroupByOutputType[P]>
      }
    >
  > 



export type sppd_detailWhereInput = {
  AND?: Prisma.sppd_detailWhereInput | Prisma.sppd_detailWhereInput[]
  OR?: Prisma.sppd_detailWhereInput[]
  NOT?: Prisma.sppd_detailWhereInput | Prisma.sppd_detailWhereInput[]
  sppd_detail_id?: Prisma.StringFilter<"sppd_detail"> | string
  step?: Prisma.IntFilter<"sppd_detail"> | number
  sppd_id?: Prisma.StringNullableFilter<"sppd_detail"> | string | null
  payroll?: Prisma.StringNullableFilter<"sppd_detail"> | string | null
  description?: Prisma.StringFilter<"sppd_detail"> | string
  employee?: Prisma.XOR<Prisma.EmployeeNullableScalarRelationFilter, Prisma.employeeWhereInput> | null
  sppd?: Prisma.XOR<Prisma.SppdNullableScalarRelationFilter, Prisma.sppdWhereInput> | null
}

export type sppd_detailOrderByWithRelationInput = {
  sppd_detail_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  sppd_id?: Prisma.SortOrderInput | Prisma.SortOrder
  payroll?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  employee?: Prisma.employeeOrderByWithRelationInput
  sppd?: Prisma.sppdOrderByWithRelationInput
  _relevance?: Prisma.sppd_detailOrderByRelevanceInput
}

export type sppd_detailWhereUniqueInput = Prisma.AtLeast<{
  sppd_detail_id?: string
  AND?: Prisma.sppd_detailWhereInput | Prisma.sppd_detailWhereInput[]
  OR?: Prisma.sppd_detailWhereInput[]
  NOT?: Prisma.sppd_detailWhereInput | Prisma.sppd_detailWhereInput[]
  step?: Prisma.IntFilter<"sppd_detail"> | number
  sppd_id?: Prisma.StringNullableFilter<"sppd_detail"> | string | null
  payroll?: Prisma.StringNullableFilter<"sppd_detail"> | string | null
  description?: Prisma.StringFilter<"sppd_detail"> | string
  employee?: Prisma.XOR<Prisma.EmployeeNullableScalarRelationFilter, Prisma.employeeWhereInput> | null
  sppd?: Prisma.XOR<Prisma.SppdNullableScalarRelationFilter, Prisma.sppdWhereInput> | null
}, "sppd_detail_id">

export type sppd_detailOrderByWithAggregationInput = {
  sppd_detail_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  sppd_id?: Prisma.SortOrderInput | Prisma.SortOrder
  payroll?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  _count?: Prisma.sppd_detailCountOrderByAggregateInput
  _avg?: Prisma.sppd_detailAvgOrderByAggregateInput
  _max?: Prisma.sppd_detailMaxOrderByAggregateInput
  _min?: Prisma.sppd_detailMinOrderByAggregateInput
  _sum?: Prisma.sppd_detailSumOrderByAggregateInput
}

export type sppd_detailScalarWhereWithAggregatesInput = {
  AND?: Prisma.sppd_detailScalarWhereWithAggregatesInput | Prisma.sppd_detailScalarWhereWithAggregatesInput[]
  OR?: Prisma.sppd_detailScalarWhereWithAggregatesInput[]
  NOT?: Prisma.sppd_detailScalarWhereWithAggregatesInput | Prisma.sppd_detailScalarWhereWithAggregatesInput[]
  sppd_detail_id?: Prisma.StringWithAggregatesFilter<"sppd_detail"> | string
  step?: Prisma.IntWithAggregatesFilter<"sppd_detail"> | number
  sppd_id?: Prisma.StringNullableWithAggregatesFilter<"sppd_detail"> | string | null
  payroll?: Prisma.StringNullableWithAggregatesFilter<"sppd_detail"> | string | null
  description?: Prisma.StringWithAggregatesFilter<"sppd_detail"> | string
}

export type sppd_detailCreateInput = {
  sppd_detail_id: string
  step: number
  description: string
  employee?: Prisma.employeeCreateNestedOneWithoutSppd_detailInput
  sppd?: Prisma.sppdCreateNestedOneWithoutSppd_detailInput
}

export type sppd_detailUncheckedCreateInput = {
  sppd_detail_id: string
  step: number
  sppd_id?: string | null
  payroll?: string | null
  description: string
}

export type sppd_detailUpdateInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  employee?: Prisma.employeeUpdateOneWithoutSppd_detailNestedInput
  sppd?: Prisma.sppdUpdateOneWithoutSppd_detailNestedInput
}

export type sppd_detailUncheckedUpdateInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  sppd_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payroll?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sppd_detailCreateManyInput = {
  sppd_detail_id: string
  step: number
  sppd_id?: string | null
  payroll?: string | null
  description: string
}

export type sppd_detailUpdateManyMutationInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sppd_detailUncheckedUpdateManyInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  sppd_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payroll?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Sppd_detailListRelationFilter = {
  every?: Prisma.sppd_detailWhereInput
  some?: Prisma.sppd_detailWhereInput
  none?: Prisma.sppd_detailWhereInput
}

export type sppd_detailOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type sppd_detailOrderByRelevanceInput = {
  fields: Prisma.sppd_detailOrderByRelevanceFieldEnum | Prisma.sppd_detailOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type sppd_detailCountOrderByAggregateInput = {
  sppd_detail_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  sppd_id?: Prisma.SortOrder
  payroll?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type sppd_detailAvgOrderByAggregateInput = {
  step?: Prisma.SortOrder
}

export type sppd_detailMaxOrderByAggregateInput = {
  sppd_detail_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  sppd_id?: Prisma.SortOrder
  payroll?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type sppd_detailMinOrderByAggregateInput = {
  sppd_detail_id?: Prisma.SortOrder
  step?: Prisma.SortOrder
  sppd_id?: Prisma.SortOrder
  payroll?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type sppd_detailSumOrderByAggregateInput = {
  step?: Prisma.SortOrder
}

export type sppd_detailCreateNestedManyWithoutEmployeeInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutEmployeeInput, Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput> | Prisma.sppd_detailCreateWithoutEmployeeInput[] | Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput | Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput[]
  createMany?: Prisma.sppd_detailCreateManyEmployeeInputEnvelope
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
}

export type sppd_detailUncheckedCreateNestedManyWithoutEmployeeInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutEmployeeInput, Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput> | Prisma.sppd_detailCreateWithoutEmployeeInput[] | Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput | Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput[]
  createMany?: Prisma.sppd_detailCreateManyEmployeeInputEnvelope
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
}

export type sppd_detailUpdateManyWithoutEmployeeNestedInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutEmployeeInput, Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput> | Prisma.sppd_detailCreateWithoutEmployeeInput[] | Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput | Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput[]
  upsert?: Prisma.sppd_detailUpsertWithWhereUniqueWithoutEmployeeInput | Prisma.sppd_detailUpsertWithWhereUniqueWithoutEmployeeInput[]
  createMany?: Prisma.sppd_detailCreateManyEmployeeInputEnvelope
  set?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  disconnect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  delete?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  update?: Prisma.sppd_detailUpdateWithWhereUniqueWithoutEmployeeInput | Prisma.sppd_detailUpdateWithWhereUniqueWithoutEmployeeInput[]
  updateMany?: Prisma.sppd_detailUpdateManyWithWhereWithoutEmployeeInput | Prisma.sppd_detailUpdateManyWithWhereWithoutEmployeeInput[]
  deleteMany?: Prisma.sppd_detailScalarWhereInput | Prisma.sppd_detailScalarWhereInput[]
}

export type sppd_detailUncheckedUpdateManyWithoutEmployeeNestedInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutEmployeeInput, Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput> | Prisma.sppd_detailCreateWithoutEmployeeInput[] | Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput | Prisma.sppd_detailCreateOrConnectWithoutEmployeeInput[]
  upsert?: Prisma.sppd_detailUpsertWithWhereUniqueWithoutEmployeeInput | Prisma.sppd_detailUpsertWithWhereUniqueWithoutEmployeeInput[]
  createMany?: Prisma.sppd_detailCreateManyEmployeeInputEnvelope
  set?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  disconnect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  delete?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  update?: Prisma.sppd_detailUpdateWithWhereUniqueWithoutEmployeeInput | Prisma.sppd_detailUpdateWithWhereUniqueWithoutEmployeeInput[]
  updateMany?: Prisma.sppd_detailUpdateManyWithWhereWithoutEmployeeInput | Prisma.sppd_detailUpdateManyWithWhereWithoutEmployeeInput[]
  deleteMany?: Prisma.sppd_detailScalarWhereInput | Prisma.sppd_detailScalarWhereInput[]
}

export type sppd_detailCreateNestedManyWithoutSppdInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutSppdInput, Prisma.sppd_detailUncheckedCreateWithoutSppdInput> | Prisma.sppd_detailCreateWithoutSppdInput[] | Prisma.sppd_detailUncheckedCreateWithoutSppdInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutSppdInput | Prisma.sppd_detailCreateOrConnectWithoutSppdInput[]
  createMany?: Prisma.sppd_detailCreateManySppdInputEnvelope
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
}

export type sppd_detailUncheckedCreateNestedManyWithoutSppdInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutSppdInput, Prisma.sppd_detailUncheckedCreateWithoutSppdInput> | Prisma.sppd_detailCreateWithoutSppdInput[] | Prisma.sppd_detailUncheckedCreateWithoutSppdInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutSppdInput | Prisma.sppd_detailCreateOrConnectWithoutSppdInput[]
  createMany?: Prisma.sppd_detailCreateManySppdInputEnvelope
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
}

export type sppd_detailUpdateManyWithoutSppdNestedInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutSppdInput, Prisma.sppd_detailUncheckedCreateWithoutSppdInput> | Prisma.sppd_detailCreateWithoutSppdInput[] | Prisma.sppd_detailUncheckedCreateWithoutSppdInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutSppdInput | Prisma.sppd_detailCreateOrConnectWithoutSppdInput[]
  upsert?: Prisma.sppd_detailUpsertWithWhereUniqueWithoutSppdInput | Prisma.sppd_detailUpsertWithWhereUniqueWithoutSppdInput[]
  createMany?: Prisma.sppd_detailCreateManySppdInputEnvelope
  set?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  disconnect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  delete?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  update?: Prisma.sppd_detailUpdateWithWhereUniqueWithoutSppdInput | Prisma.sppd_detailUpdateWithWhereUniqueWithoutSppdInput[]
  updateMany?: Prisma.sppd_detailUpdateManyWithWhereWithoutSppdInput | Prisma.sppd_detailUpdateManyWithWhereWithoutSppdInput[]
  deleteMany?: Prisma.sppd_detailScalarWhereInput | Prisma.sppd_detailScalarWhereInput[]
}

export type sppd_detailUncheckedUpdateManyWithoutSppdNestedInput = {
  create?: Prisma.XOR<Prisma.sppd_detailCreateWithoutSppdInput, Prisma.sppd_detailUncheckedCreateWithoutSppdInput> | Prisma.sppd_detailCreateWithoutSppdInput[] | Prisma.sppd_detailUncheckedCreateWithoutSppdInput[]
  connectOrCreate?: Prisma.sppd_detailCreateOrConnectWithoutSppdInput | Prisma.sppd_detailCreateOrConnectWithoutSppdInput[]
  upsert?: Prisma.sppd_detailUpsertWithWhereUniqueWithoutSppdInput | Prisma.sppd_detailUpsertWithWhereUniqueWithoutSppdInput[]
  createMany?: Prisma.sppd_detailCreateManySppdInputEnvelope
  set?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  disconnect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  delete?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  connect?: Prisma.sppd_detailWhereUniqueInput | Prisma.sppd_detailWhereUniqueInput[]
  update?: Prisma.sppd_detailUpdateWithWhereUniqueWithoutSppdInput | Prisma.sppd_detailUpdateWithWhereUniqueWithoutSppdInput[]
  updateMany?: Prisma.sppd_detailUpdateManyWithWhereWithoutSppdInput | Prisma.sppd_detailUpdateManyWithWhereWithoutSppdInput[]
  deleteMany?: Prisma.sppd_detailScalarWhereInput | Prisma.sppd_detailScalarWhereInput[]
}

export type sppd_detailCreateWithoutEmployeeInput = {
  sppd_detail_id: string
  step: number
  description: string
  sppd?: Prisma.sppdCreateNestedOneWithoutSppd_detailInput
}

export type sppd_detailUncheckedCreateWithoutEmployeeInput = {
  sppd_detail_id: string
  step: number
  sppd_id?: string | null
  description: string
}

export type sppd_detailCreateOrConnectWithoutEmployeeInput = {
  where: Prisma.sppd_detailWhereUniqueInput
  create: Prisma.XOR<Prisma.sppd_detailCreateWithoutEmployeeInput, Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput>
}

export type sppd_detailCreateManyEmployeeInputEnvelope = {
  data: Prisma.sppd_detailCreateManyEmployeeInput | Prisma.sppd_detailCreateManyEmployeeInput[]
  skipDuplicates?: boolean
}

export type sppd_detailUpsertWithWhereUniqueWithoutEmployeeInput = {
  where: Prisma.sppd_detailWhereUniqueInput
  update: Prisma.XOR<Prisma.sppd_detailUpdateWithoutEmployeeInput, Prisma.sppd_detailUncheckedUpdateWithoutEmployeeInput>
  create: Prisma.XOR<Prisma.sppd_detailCreateWithoutEmployeeInput, Prisma.sppd_detailUncheckedCreateWithoutEmployeeInput>
}

export type sppd_detailUpdateWithWhereUniqueWithoutEmployeeInput = {
  where: Prisma.sppd_detailWhereUniqueInput
  data: Prisma.XOR<Prisma.sppd_detailUpdateWithoutEmployeeInput, Prisma.sppd_detailUncheckedUpdateWithoutEmployeeInput>
}

export type sppd_detailUpdateManyWithWhereWithoutEmployeeInput = {
  where: Prisma.sppd_detailScalarWhereInput
  data: Prisma.XOR<Prisma.sppd_detailUpdateManyMutationInput, Prisma.sppd_detailUncheckedUpdateManyWithoutEmployeeInput>
}

export type sppd_detailScalarWhereInput = {
  AND?: Prisma.sppd_detailScalarWhereInput | Prisma.sppd_detailScalarWhereInput[]
  OR?: Prisma.sppd_detailScalarWhereInput[]
  NOT?: Prisma.sppd_detailScalarWhereInput | Prisma.sppd_detailScalarWhereInput[]
  sppd_detail_id?: Prisma.StringFilter<"sppd_detail"> | string
  step?: Prisma.IntFilter<"sppd_detail"> | number
  sppd_id?: Prisma.StringNullableFilter<"sppd_detail"> | string | null
  payroll?: Prisma.StringNullableFilter<"sppd_detail"> | string | null
  description?: Prisma.StringFilter<"sppd_detail"> | string
}

export type sppd_detailCreateWithoutSppdInput = {
  sppd_detail_id: string
  step: number
  description: string
  employee?: Prisma.employeeCreateNestedOneWithoutSppd_detailInput
}

export type sppd_detailUncheckedCreateWithoutSppdInput = {
  sppd_detail_id: string
  step: number
  payroll?: string | null
  description: string
}

export type sppd_detailCreateOrConnectWithoutSppdInput = {
  where: Prisma.sppd_detailWhereUniqueInput
  create: Prisma.XOR<Prisma.sppd_detailCreateWithoutSppdInput, Prisma.sppd_detailUncheckedCreateWithoutSppdInput>
}

export type sppd_detailCreateManySppdInputEnvelope = {
  data: Prisma.sppd_detailCreateManySppdInput | Prisma.sppd_detailCreateManySppdInput[]
  skipDuplicates?: boolean
}

export type sppd_detailUpsertWithWhereUniqueWithoutSppdInput = {
  where: Prisma.sppd_detailWhereUniqueInput
  update: Prisma.XOR<Prisma.sppd_detailUpdateWithoutSppdInput, Prisma.sppd_detailUncheckedUpdateWithoutSppdInput>
  create: Prisma.XOR<Prisma.sppd_detailCreateWithoutSppdInput, Prisma.sppd_detailUncheckedCreateWithoutSppdInput>
}

export type sppd_detailUpdateWithWhereUniqueWithoutSppdInput = {
  where: Prisma.sppd_detailWhereUniqueInput
  data: Prisma.XOR<Prisma.sppd_detailUpdateWithoutSppdInput, Prisma.sppd_detailUncheckedUpdateWithoutSppdInput>
}

export type sppd_detailUpdateManyWithWhereWithoutSppdInput = {
  where: Prisma.sppd_detailScalarWhereInput
  data: Prisma.XOR<Prisma.sppd_detailUpdateManyMutationInput, Prisma.sppd_detailUncheckedUpdateManyWithoutSppdInput>
}

export type sppd_detailCreateManyEmployeeInput = {
  sppd_detail_id: string
  step: number
  sppd_id?: string | null
  description: string
}

export type sppd_detailUpdateWithoutEmployeeInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  sppd?: Prisma.sppdUpdateOneWithoutSppd_detailNestedInput
}

export type sppd_detailUncheckedUpdateWithoutEmployeeInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  sppd_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sppd_detailUncheckedUpdateManyWithoutEmployeeInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  sppd_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sppd_detailCreateManySppdInput = {
  sppd_detail_id: string
  step: number
  payroll?: string | null
  description: string
}

export type sppd_detailUpdateWithoutSppdInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  employee?: Prisma.employeeUpdateOneWithoutSppd_detailNestedInput
}

export type sppd_detailUncheckedUpdateWithoutSppdInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  payroll?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sppd_detailUncheckedUpdateManyWithoutSppdInput = {
  sppd_detail_id?: Prisma.StringFieldUpdateOperationsInput | string
  step?: Prisma.IntFieldUpdateOperationsInput | number
  payroll?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
}



export type sppd_detailSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  sppd_detail_id?: boolean
  step?: boolean
  sppd_id?: boolean
  payroll?: boolean
  description?: boolean
  employee?: boolean | Prisma.sppd_detail$employeeArgs<ExtArgs>
  sppd?: boolean | Prisma.sppd_detail$sppdArgs<ExtArgs>
}, ExtArgs["result"]["sppd_detail"]>



export type sppd_detailSelectScalar = {
  sppd_detail_id?: boolean
  step?: boolean
  sppd_id?: boolean
  payroll?: boolean
  description?: boolean
}

export type sppd_detailOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"sppd_detail_id" | "step" | "sppd_id" | "payroll" | "description", ExtArgs["result"]["sppd_detail"]>
export type sppd_detailInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employee?: boolean | Prisma.sppd_detail$employeeArgs<ExtArgs>
  sppd?: boolean | Prisma.sppd_detail$sppdArgs<ExtArgs>
}

export type $sppd_detailPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "sppd_detail"
  objects: {
    employee: Prisma.$employeePayload<ExtArgs> | null
    sppd: Prisma.$sppdPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    sppd_detail_id: string
    step: number
    sppd_id: string | null
    payroll: string | null
    description: string
  }, ExtArgs["result"]["sppd_detail"]>
  composites: {}
}

export type sppd_detailGetPayload<S extends boolean | null | undefined | sppd_detailDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload, S>

export type sppd_detailCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<sppd_detailFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Sppd_detailCountAggregateInputType | true
  }

export interface sppd_detailDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['sppd_detail'], meta: { name: 'sppd_detail' } }
  /**
   * Find zero or one Sppd_detail that matches the filter.
   * @param {sppd_detailFindUniqueArgs} args - Arguments to find a Sppd_detail
   * @example
   * // Get one Sppd_detail
   * const sppd_detail = await prisma.sppd_detail.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends sppd_detailFindUniqueArgs>(args: Prisma.SelectSubset<T, sppd_detailFindUniqueArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Sppd_detail that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {sppd_detailFindUniqueOrThrowArgs} args - Arguments to find a Sppd_detail
   * @example
   * // Get one Sppd_detail
   * const sppd_detail = await prisma.sppd_detail.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends sppd_detailFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, sppd_detailFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sppd_detail that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sppd_detailFindFirstArgs} args - Arguments to find a Sppd_detail
   * @example
   * // Get one Sppd_detail
   * const sppd_detail = await prisma.sppd_detail.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends sppd_detailFindFirstArgs>(args?: Prisma.SelectSubset<T, sppd_detailFindFirstArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sppd_detail that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sppd_detailFindFirstOrThrowArgs} args - Arguments to find a Sppd_detail
   * @example
   * // Get one Sppd_detail
   * const sppd_detail = await prisma.sppd_detail.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends sppd_detailFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, sppd_detailFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sppd_details that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sppd_detailFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sppd_details
   * const sppd_details = await prisma.sppd_detail.findMany()
   * 
   * // Get first 10 Sppd_details
   * const sppd_details = await prisma.sppd_detail.findMany({ take: 10 })
   * 
   * // Only select the `sppd_detail_id`
   * const sppd_detailWithSppd_detail_idOnly = await prisma.sppd_detail.findMany({ select: { sppd_detail_id: true } })
   * 
   */
  findMany<T extends sppd_detailFindManyArgs>(args?: Prisma.SelectSubset<T, sppd_detailFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Sppd_detail.
   * @param {sppd_detailCreateArgs} args - Arguments to create a Sppd_detail.
   * @example
   * // Create one Sppd_detail
   * const Sppd_detail = await prisma.sppd_detail.create({
   *   data: {
   *     // ... data to create a Sppd_detail
   *   }
   * })
   * 
   */
  create<T extends sppd_detailCreateArgs>(args: Prisma.SelectSubset<T, sppd_detailCreateArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sppd_details.
   * @param {sppd_detailCreateManyArgs} args - Arguments to create many Sppd_details.
   * @example
   * // Create many Sppd_details
   * const sppd_detail = await prisma.sppd_detail.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends sppd_detailCreateManyArgs>(args?: Prisma.SelectSubset<T, sppd_detailCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Sppd_detail.
   * @param {sppd_detailDeleteArgs} args - Arguments to delete one Sppd_detail.
   * @example
   * // Delete one Sppd_detail
   * const Sppd_detail = await prisma.sppd_detail.delete({
   *   where: {
   *     // ... filter to delete one Sppd_detail
   *   }
   * })
   * 
   */
  delete<T extends sppd_detailDeleteArgs>(args: Prisma.SelectSubset<T, sppd_detailDeleteArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Sppd_detail.
   * @param {sppd_detailUpdateArgs} args - Arguments to update one Sppd_detail.
   * @example
   * // Update one Sppd_detail
   * const sppd_detail = await prisma.sppd_detail.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends sppd_detailUpdateArgs>(args: Prisma.SelectSubset<T, sppd_detailUpdateArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sppd_details.
   * @param {sppd_detailDeleteManyArgs} args - Arguments to filter Sppd_details to delete.
   * @example
   * // Delete a few Sppd_details
   * const { count } = await prisma.sppd_detail.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends sppd_detailDeleteManyArgs>(args?: Prisma.SelectSubset<T, sppd_detailDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sppd_details.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sppd_detailUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sppd_details
   * const sppd_detail = await prisma.sppd_detail.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends sppd_detailUpdateManyArgs>(args: Prisma.SelectSubset<T, sppd_detailUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Sppd_detail.
   * @param {sppd_detailUpsertArgs} args - Arguments to update or create a Sppd_detail.
   * @example
   * // Update or create a Sppd_detail
   * const sppd_detail = await prisma.sppd_detail.upsert({
   *   create: {
   *     // ... data to create a Sppd_detail
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Sppd_detail we want to update
   *   }
   * })
   */
  upsert<T extends sppd_detailUpsertArgs>(args: Prisma.SelectSubset<T, sppd_detailUpsertArgs<ExtArgs>>): Prisma.Prisma__sppd_detailClient<runtime.Types.Result.GetResult<Prisma.$sppd_detailPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sppd_details.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sppd_detailCountArgs} args - Arguments to filter Sppd_details to count.
   * @example
   * // Count the number of Sppd_details
   * const count = await prisma.sppd_detail.count({
   *   where: {
   *     // ... the filter for the Sppd_details we want to count
   *   }
   * })
  **/
  count<T extends sppd_detailCountArgs>(
    args?: Prisma.Subset<T, sppd_detailCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Sppd_detailCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Sppd_detail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Sppd_detailAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Sppd_detailAggregateArgs>(args: Prisma.Subset<T, Sppd_detailAggregateArgs>): Prisma.PrismaPromise<GetSppd_detailAggregateType<T>>

  /**
   * Group by Sppd_detail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sppd_detailGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends sppd_detailGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: sppd_detailGroupByArgs['orderBy'] }
      : { orderBy?: sppd_detailGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, sppd_detailGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSppd_detailGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the sppd_detail model
 */
readonly fields: sppd_detailFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for sppd_detail.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__sppd_detailClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  employee<T extends Prisma.sppd_detail$employeeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.sppd_detail$employeeArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  sppd<T extends Prisma.sppd_detail$sppdArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.sppd_detail$sppdArgs<ExtArgs>>): Prisma.Prisma__sppdClient<runtime.Types.Result.GetResult<Prisma.$sppdPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the sppd_detail model
 */
export interface sppd_detailFieldRefs {
  readonly sppd_detail_id: Prisma.FieldRef<"sppd_detail", 'String'>
  readonly step: Prisma.FieldRef<"sppd_detail", 'Int'>
  readonly sppd_id: Prisma.FieldRef<"sppd_detail", 'String'>
  readonly payroll: Prisma.FieldRef<"sppd_detail", 'String'>
  readonly description: Prisma.FieldRef<"sppd_detail", 'String'>
}
    

// Custom InputTypes
/**
 * sppd_detail findUnique
 */
export type sppd_detailFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * Filter, which sppd_detail to fetch.
   */
  where: Prisma.sppd_detailWhereUniqueInput
}

/**
 * sppd_detail findUniqueOrThrow
 */
export type sppd_detailFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * Filter, which sppd_detail to fetch.
   */
  where: Prisma.sppd_detailWhereUniqueInput
}

/**
 * sppd_detail findFirst
 */
export type sppd_detailFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * Filter, which sppd_detail to fetch.
   */
  where?: Prisma.sppd_detailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sppd_details to fetch.
   */
  orderBy?: Prisma.sppd_detailOrderByWithRelationInput | Prisma.sppd_detailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for sppd_details.
   */
  cursor?: Prisma.sppd_detailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sppd_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sppd_details.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of sppd_details.
   */
  distinct?: Prisma.Sppd_detailScalarFieldEnum | Prisma.Sppd_detailScalarFieldEnum[]
}

/**
 * sppd_detail findFirstOrThrow
 */
export type sppd_detailFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * Filter, which sppd_detail to fetch.
   */
  where?: Prisma.sppd_detailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sppd_details to fetch.
   */
  orderBy?: Prisma.sppd_detailOrderByWithRelationInput | Prisma.sppd_detailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for sppd_details.
   */
  cursor?: Prisma.sppd_detailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sppd_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sppd_details.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of sppd_details.
   */
  distinct?: Prisma.Sppd_detailScalarFieldEnum | Prisma.Sppd_detailScalarFieldEnum[]
}

/**
 * sppd_detail findMany
 */
export type sppd_detailFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * Filter, which sppd_details to fetch.
   */
  where?: Prisma.sppd_detailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sppd_details to fetch.
   */
  orderBy?: Prisma.sppd_detailOrderByWithRelationInput | Prisma.sppd_detailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing sppd_details.
   */
  cursor?: Prisma.sppd_detailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sppd_details from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sppd_details.
   */
  skip?: number
  distinct?: Prisma.Sppd_detailScalarFieldEnum | Prisma.Sppd_detailScalarFieldEnum[]
}

/**
 * sppd_detail create
 */
export type sppd_detailCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * The data needed to create a sppd_detail.
   */
  data: Prisma.XOR<Prisma.sppd_detailCreateInput, Prisma.sppd_detailUncheckedCreateInput>
}

/**
 * sppd_detail createMany
 */
export type sppd_detailCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many sppd_details.
   */
  data: Prisma.sppd_detailCreateManyInput | Prisma.sppd_detailCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * sppd_detail update
 */
export type sppd_detailUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * The data needed to update a sppd_detail.
   */
  data: Prisma.XOR<Prisma.sppd_detailUpdateInput, Prisma.sppd_detailUncheckedUpdateInput>
  /**
   * Choose, which sppd_detail to update.
   */
  where: Prisma.sppd_detailWhereUniqueInput
}

/**
 * sppd_detail updateMany
 */
export type sppd_detailUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update sppd_details.
   */
  data: Prisma.XOR<Prisma.sppd_detailUpdateManyMutationInput, Prisma.sppd_detailUncheckedUpdateManyInput>
  /**
   * Filter which sppd_details to update
   */
  where?: Prisma.sppd_detailWhereInput
  /**
   * Limit how many sppd_details to update.
   */
  limit?: number
}

/**
 * sppd_detail upsert
 */
export type sppd_detailUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * The filter to search for the sppd_detail to update in case it exists.
   */
  where: Prisma.sppd_detailWhereUniqueInput
  /**
   * In case the sppd_detail found by the `where` argument doesn't exist, create a new sppd_detail with this data.
   */
  create: Prisma.XOR<Prisma.sppd_detailCreateInput, Prisma.sppd_detailUncheckedCreateInput>
  /**
   * In case the sppd_detail was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.sppd_detailUpdateInput, Prisma.sppd_detailUncheckedUpdateInput>
}

/**
 * sppd_detail delete
 */
export type sppd_detailDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
  /**
   * Filter which sppd_detail to delete.
   */
  where: Prisma.sppd_detailWhereUniqueInput
}

/**
 * sppd_detail deleteMany
 */
export type sppd_detailDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which sppd_details to delete
   */
  where?: Prisma.sppd_detailWhereInput
  /**
   * Limit how many sppd_details to delete.
   */
  limit?: number
}

/**
 * sppd_detail.employee
 */
export type sppd_detail$employeeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  where?: Prisma.employeeWhereInput
}

/**
 * sppd_detail.sppd
 */
export type sppd_detail$sppdArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd
   */
  select?: Prisma.sppdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd
   */
  omit?: Prisma.sppdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppdInclude<ExtArgs> | null
  where?: Prisma.sppdWhereInput
}

/**
 * sppd_detail without action
 */
export type sppd_detailDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the sppd_detail
   */
  select?: Prisma.sppd_detailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the sppd_detail
   */
  omit?: Prisma.sppd_detailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.sppd_detailInclude<ExtArgs> | null
}
