
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `temp_check_io` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model temp_check_io
 * 
 */
export type temp_check_ioModel = runtime.Types.Result.DefaultSelection<Prisma.$temp_check_ioPayload>

export type AggregateTemp_check_io = {
  _count: Temp_check_ioCountAggregateOutputType | null
  _avg: Temp_check_ioAvgAggregateOutputType | null
  _sum: Temp_check_ioSumAggregateOutputType | null
  _min: Temp_check_ioMinAggregateOutputType | null
  _max: Temp_check_ioMaxAggregateOutputType | null
}

export type Temp_check_ioAvgAggregateOutputType = {
  machine_no: number | null
}

export type Temp_check_ioSumAggregateOutputType = {
  machine_no: number | null
}

export type Temp_check_ioMinAggregateOutputType = {
  check_io_id: string | null
  user_id_machine: string | null
  datetime: Date | null
  type: string | null
  machine_no: number | null
}

export type Temp_check_ioMaxAggregateOutputType = {
  check_io_id: string | null
  user_id_machine: string | null
  datetime: Date | null
  type: string | null
  machine_no: number | null
}

export type Temp_check_ioCountAggregateOutputType = {
  check_io_id: number
  user_id_machine: number
  datetime: number
  type: number
  machine_no: number
  _all: number
}


export type Temp_check_ioAvgAggregateInputType = {
  machine_no?: true
}

export type Temp_check_ioSumAggregateInputType = {
  machine_no?: true
}

export type Temp_check_ioMinAggregateInputType = {
  check_io_id?: true
  user_id_machine?: true
  datetime?: true
  type?: true
  machine_no?: true
}

export type Temp_check_ioMaxAggregateInputType = {
  check_io_id?: true
  user_id_machine?: true
  datetime?: true
  type?: true
  machine_no?: true
}

export type Temp_check_ioCountAggregateInputType = {
  check_io_id?: true
  user_id_machine?: true
  datetime?: true
  type?: true
  machine_no?: true
  _all?: true
}

export type Temp_check_ioAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which temp_check_io to aggregate.
   */
  where?: Prisma.temp_check_ioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of temp_check_ios to fetch.
   */
  orderBy?: Prisma.temp_check_ioOrderByWithRelationInput | Prisma.temp_check_ioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.temp_check_ioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` temp_check_ios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` temp_check_ios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned temp_check_ios
  **/
  _count?: true | Temp_check_ioCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Temp_check_ioAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Temp_check_ioSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Temp_check_ioMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Temp_check_ioMaxAggregateInputType
}

export type GetTemp_check_ioAggregateType<T extends Temp_check_ioAggregateArgs> = {
      [P in keyof T & keyof AggregateTemp_check_io]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTemp_check_io[P]>
    : Prisma.GetScalarType<T[P], AggregateTemp_check_io[P]>
}




export type temp_check_ioGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.temp_check_ioWhereInput
  orderBy?: Prisma.temp_check_ioOrderByWithAggregationInput | Prisma.temp_check_ioOrderByWithAggregationInput[]
  by: Prisma.Temp_check_ioScalarFieldEnum[] | Prisma.Temp_check_ioScalarFieldEnum
  having?: Prisma.temp_check_ioScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Temp_check_ioCountAggregateInputType | true
  _avg?: Temp_check_ioAvgAggregateInputType
  _sum?: Temp_check_ioSumAggregateInputType
  _min?: Temp_check_ioMinAggregateInputType
  _max?: Temp_check_ioMaxAggregateInputType
}

export type Temp_check_ioGroupByOutputType = {
  check_io_id: string
  user_id_machine: string
  datetime: Date
  type: string
  machine_no: number | null
  _count: Temp_check_ioCountAggregateOutputType | null
  _avg: Temp_check_ioAvgAggregateOutputType | null
  _sum: Temp_check_ioSumAggregateOutputType | null
  _min: Temp_check_ioMinAggregateOutputType | null
  _max: Temp_check_ioMaxAggregateOutputType | null
}

type GetTemp_check_ioGroupByPayload<T extends temp_check_ioGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Temp_check_ioGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Temp_check_ioGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Temp_check_ioGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Temp_check_ioGroupByOutputType[P]>
      }
    >
  > 



export type temp_check_ioWhereInput = {
  AND?: Prisma.temp_check_ioWhereInput | Prisma.temp_check_ioWhereInput[]
  OR?: Prisma.temp_check_ioWhereInput[]
  NOT?: Prisma.temp_check_ioWhereInput | Prisma.temp_check_ioWhereInput[]
  check_io_id?: Prisma.StringFilter<"temp_check_io"> | string
  user_id_machine?: Prisma.StringFilter<"temp_check_io"> | string
  datetime?: Prisma.DateTimeFilter<"temp_check_io"> | Date | string
  type?: Prisma.StringFilter<"temp_check_io"> | string
  machine_no?: Prisma.IntNullableFilter<"temp_check_io"> | number | null
}

export type temp_check_ioOrderByWithRelationInput = {
  check_io_id?: Prisma.SortOrder
  user_id_machine?: Prisma.SortOrder
  datetime?: Prisma.SortOrder
  type?: Prisma.SortOrder
  machine_no?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.temp_check_ioOrderByRelevanceInput
}

export type temp_check_ioWhereUniqueInput = Prisma.AtLeast<{
  check_io_id?: string
  AND?: Prisma.temp_check_ioWhereInput | Prisma.temp_check_ioWhereInput[]
  OR?: Prisma.temp_check_ioWhereInput[]
  NOT?: Prisma.temp_check_ioWhereInput | Prisma.temp_check_ioWhereInput[]
  user_id_machine?: Prisma.StringFilter<"temp_check_io"> | string
  datetime?: Prisma.DateTimeFilter<"temp_check_io"> | Date | string
  type?: Prisma.StringFilter<"temp_check_io"> | string
  machine_no?: Prisma.IntNullableFilter<"temp_check_io"> | number | null
}, "check_io_id">

export type temp_check_ioOrderByWithAggregationInput = {
  check_io_id?: Prisma.SortOrder
  user_id_machine?: Prisma.SortOrder
  datetime?: Prisma.SortOrder
  type?: Prisma.SortOrder
  machine_no?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.temp_check_ioCountOrderByAggregateInput
  _avg?: Prisma.temp_check_ioAvgOrderByAggregateInput
  _max?: Prisma.temp_check_ioMaxOrderByAggregateInput
  _min?: Prisma.temp_check_ioMinOrderByAggregateInput
  _sum?: Prisma.temp_check_ioSumOrderByAggregateInput
}

export type temp_check_ioScalarWhereWithAggregatesInput = {
  AND?: Prisma.temp_check_ioScalarWhereWithAggregatesInput | Prisma.temp_check_ioScalarWhereWithAggregatesInput[]
  OR?: Prisma.temp_check_ioScalarWhereWithAggregatesInput[]
  NOT?: Prisma.temp_check_ioScalarWhereWithAggregatesInput | Prisma.temp_check_ioScalarWhereWithAggregatesInput[]
  check_io_id?: Prisma.StringWithAggregatesFilter<"temp_check_io"> | string
  user_id_machine?: Prisma.StringWithAggregatesFilter<"temp_check_io"> | string
  datetime?: Prisma.DateTimeWithAggregatesFilter<"temp_check_io"> | Date | string
  type?: Prisma.StringWithAggregatesFilter<"temp_check_io"> | string
  machine_no?: Prisma.IntNullableWithAggregatesFilter<"temp_check_io"> | number | null
}

export type temp_check_ioCreateInput = {
  check_io_id: string
  user_id_machine: string
  datetime: Date | string
  type: string
  machine_no?: number | null
}

export type temp_check_ioUncheckedCreateInput = {
  check_io_id: string
  user_id_machine: string
  datetime: Date | string
  type: string
  machine_no?: number | null
}

export type temp_check_ioUpdateInput = {
  check_io_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id_machine?: Prisma.StringFieldUpdateOperationsInput | string
  datetime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  machine_no?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type temp_check_ioUncheckedUpdateInput = {
  check_io_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id_machine?: Prisma.StringFieldUpdateOperationsInput | string
  datetime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  machine_no?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type temp_check_ioCreateManyInput = {
  check_io_id: string
  user_id_machine: string
  datetime: Date | string
  type: string
  machine_no?: number | null
}

export type temp_check_ioUpdateManyMutationInput = {
  check_io_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id_machine?: Prisma.StringFieldUpdateOperationsInput | string
  datetime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  machine_no?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type temp_check_ioUncheckedUpdateManyInput = {
  check_io_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id_machine?: Prisma.StringFieldUpdateOperationsInput | string
  datetime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  machine_no?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type temp_check_ioOrderByRelevanceInput = {
  fields: Prisma.temp_check_ioOrderByRelevanceFieldEnum | Prisma.temp_check_ioOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type temp_check_ioCountOrderByAggregateInput = {
  check_io_id?: Prisma.SortOrder
  user_id_machine?: Prisma.SortOrder
  datetime?: Prisma.SortOrder
  type?: Prisma.SortOrder
  machine_no?: Prisma.SortOrder
}

export type temp_check_ioAvgOrderByAggregateInput = {
  machine_no?: Prisma.SortOrder
}

export type temp_check_ioMaxOrderByAggregateInput = {
  check_io_id?: Prisma.SortOrder
  user_id_machine?: Prisma.SortOrder
  datetime?: Prisma.SortOrder
  type?: Prisma.SortOrder
  machine_no?: Prisma.SortOrder
}

export type temp_check_ioMinOrderByAggregateInput = {
  check_io_id?: Prisma.SortOrder
  user_id_machine?: Prisma.SortOrder
  datetime?: Prisma.SortOrder
  type?: Prisma.SortOrder
  machine_no?: Prisma.SortOrder
}

export type temp_check_ioSumOrderByAggregateInput = {
  machine_no?: Prisma.SortOrder
}



export type temp_check_ioSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  check_io_id?: boolean
  user_id_machine?: boolean
  datetime?: boolean
  type?: boolean
  machine_no?: boolean
}, ExtArgs["result"]["temp_check_io"]>



export type temp_check_ioSelectScalar = {
  check_io_id?: boolean
  user_id_machine?: boolean
  datetime?: boolean
  type?: boolean
  machine_no?: boolean
}

export type temp_check_ioOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"check_io_id" | "user_id_machine" | "datetime" | "type" | "machine_no", ExtArgs["result"]["temp_check_io"]>

export type $temp_check_ioPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "temp_check_io"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    check_io_id: string
    user_id_machine: string
    datetime: Date
    type: string
    machine_no: number | null
  }, ExtArgs["result"]["temp_check_io"]>
  composites: {}
}

export type temp_check_ioGetPayload<S extends boolean | null | undefined | temp_check_ioDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload, S>

export type temp_check_ioCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<temp_check_ioFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Temp_check_ioCountAggregateInputType | true
  }

export interface temp_check_ioDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['temp_check_io'], meta: { name: 'temp_check_io' } }
  /**
   * Find zero or one Temp_check_io that matches the filter.
   * @param {temp_check_ioFindUniqueArgs} args - Arguments to find a Temp_check_io
   * @example
   * // Get one Temp_check_io
   * const temp_check_io = await prisma.temp_check_io.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends temp_check_ioFindUniqueArgs>(args: Prisma.SelectSubset<T, temp_check_ioFindUniqueArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Temp_check_io that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {temp_check_ioFindUniqueOrThrowArgs} args - Arguments to find a Temp_check_io
   * @example
   * // Get one Temp_check_io
   * const temp_check_io = await prisma.temp_check_io.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends temp_check_ioFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, temp_check_ioFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Temp_check_io that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {temp_check_ioFindFirstArgs} args - Arguments to find a Temp_check_io
   * @example
   * // Get one Temp_check_io
   * const temp_check_io = await prisma.temp_check_io.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends temp_check_ioFindFirstArgs>(args?: Prisma.SelectSubset<T, temp_check_ioFindFirstArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Temp_check_io that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {temp_check_ioFindFirstOrThrowArgs} args - Arguments to find a Temp_check_io
   * @example
   * // Get one Temp_check_io
   * const temp_check_io = await prisma.temp_check_io.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends temp_check_ioFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, temp_check_ioFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Temp_check_ios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {temp_check_ioFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Temp_check_ios
   * const temp_check_ios = await prisma.temp_check_io.findMany()
   * 
   * // Get first 10 Temp_check_ios
   * const temp_check_ios = await prisma.temp_check_io.findMany({ take: 10 })
   * 
   * // Only select the `check_io_id`
   * const temp_check_ioWithCheck_io_idOnly = await prisma.temp_check_io.findMany({ select: { check_io_id: true } })
   * 
   */
  findMany<T extends temp_check_ioFindManyArgs>(args?: Prisma.SelectSubset<T, temp_check_ioFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Temp_check_io.
   * @param {temp_check_ioCreateArgs} args - Arguments to create a Temp_check_io.
   * @example
   * // Create one Temp_check_io
   * const Temp_check_io = await prisma.temp_check_io.create({
   *   data: {
   *     // ... data to create a Temp_check_io
   *   }
   * })
   * 
   */
  create<T extends temp_check_ioCreateArgs>(args: Prisma.SelectSubset<T, temp_check_ioCreateArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Temp_check_ios.
   * @param {temp_check_ioCreateManyArgs} args - Arguments to create many Temp_check_ios.
   * @example
   * // Create many Temp_check_ios
   * const temp_check_io = await prisma.temp_check_io.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends temp_check_ioCreateManyArgs>(args?: Prisma.SelectSubset<T, temp_check_ioCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Temp_check_io.
   * @param {temp_check_ioDeleteArgs} args - Arguments to delete one Temp_check_io.
   * @example
   * // Delete one Temp_check_io
   * const Temp_check_io = await prisma.temp_check_io.delete({
   *   where: {
   *     // ... filter to delete one Temp_check_io
   *   }
   * })
   * 
   */
  delete<T extends temp_check_ioDeleteArgs>(args: Prisma.SelectSubset<T, temp_check_ioDeleteArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Temp_check_io.
   * @param {temp_check_ioUpdateArgs} args - Arguments to update one Temp_check_io.
   * @example
   * // Update one Temp_check_io
   * const temp_check_io = await prisma.temp_check_io.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends temp_check_ioUpdateArgs>(args: Prisma.SelectSubset<T, temp_check_ioUpdateArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Temp_check_ios.
   * @param {temp_check_ioDeleteManyArgs} args - Arguments to filter Temp_check_ios to delete.
   * @example
   * // Delete a few Temp_check_ios
   * const { count } = await prisma.temp_check_io.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends temp_check_ioDeleteManyArgs>(args?: Prisma.SelectSubset<T, temp_check_ioDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Temp_check_ios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {temp_check_ioUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Temp_check_ios
   * const temp_check_io = await prisma.temp_check_io.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends temp_check_ioUpdateManyArgs>(args: Prisma.SelectSubset<T, temp_check_ioUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Temp_check_io.
   * @param {temp_check_ioUpsertArgs} args - Arguments to update or create a Temp_check_io.
   * @example
   * // Update or create a Temp_check_io
   * const temp_check_io = await prisma.temp_check_io.upsert({
   *   create: {
   *     // ... data to create a Temp_check_io
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Temp_check_io we want to update
   *   }
   * })
   */
  upsert<T extends temp_check_ioUpsertArgs>(args: Prisma.SelectSubset<T, temp_check_ioUpsertArgs<ExtArgs>>): Prisma.Prisma__temp_check_ioClient<runtime.Types.Result.GetResult<Prisma.$temp_check_ioPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Temp_check_ios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {temp_check_ioCountArgs} args - Arguments to filter Temp_check_ios to count.
   * @example
   * // Count the number of Temp_check_ios
   * const count = await prisma.temp_check_io.count({
   *   where: {
   *     // ... the filter for the Temp_check_ios we want to count
   *   }
   * })
  **/
  count<T extends temp_check_ioCountArgs>(
    args?: Prisma.Subset<T, temp_check_ioCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Temp_check_ioCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Temp_check_io.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Temp_check_ioAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Temp_check_ioAggregateArgs>(args: Prisma.Subset<T, Temp_check_ioAggregateArgs>): Prisma.PrismaPromise<GetTemp_check_ioAggregateType<T>>

  /**
   * Group by Temp_check_io.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {temp_check_ioGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends temp_check_ioGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: temp_check_ioGroupByArgs['orderBy'] }
      : { orderBy?: temp_check_ioGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, temp_check_ioGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTemp_check_ioGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the temp_check_io model
 */
readonly fields: temp_check_ioFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for temp_check_io.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__temp_check_ioClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the temp_check_io model
 */
export interface temp_check_ioFieldRefs {
  readonly check_io_id: Prisma.FieldRef<"temp_check_io", 'String'>
  readonly user_id_machine: Prisma.FieldRef<"temp_check_io", 'String'>
  readonly datetime: Prisma.FieldRef<"temp_check_io", 'DateTime'>
  readonly type: Prisma.FieldRef<"temp_check_io", 'String'>
  readonly machine_no: Prisma.FieldRef<"temp_check_io", 'Int'>
}
    

// Custom InputTypes
/**
 * temp_check_io findUnique
 */
export type temp_check_ioFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * Filter, which temp_check_io to fetch.
   */
  where: Prisma.temp_check_ioWhereUniqueInput
}

/**
 * temp_check_io findUniqueOrThrow
 */
export type temp_check_ioFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * Filter, which temp_check_io to fetch.
   */
  where: Prisma.temp_check_ioWhereUniqueInput
}

/**
 * temp_check_io findFirst
 */
export type temp_check_ioFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * Filter, which temp_check_io to fetch.
   */
  where?: Prisma.temp_check_ioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of temp_check_ios to fetch.
   */
  orderBy?: Prisma.temp_check_ioOrderByWithRelationInput | Prisma.temp_check_ioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for temp_check_ios.
   */
  cursor?: Prisma.temp_check_ioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` temp_check_ios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` temp_check_ios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of temp_check_ios.
   */
  distinct?: Prisma.Temp_check_ioScalarFieldEnum | Prisma.Temp_check_ioScalarFieldEnum[]
}

/**
 * temp_check_io findFirstOrThrow
 */
export type temp_check_ioFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * Filter, which temp_check_io to fetch.
   */
  where?: Prisma.temp_check_ioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of temp_check_ios to fetch.
   */
  orderBy?: Prisma.temp_check_ioOrderByWithRelationInput | Prisma.temp_check_ioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for temp_check_ios.
   */
  cursor?: Prisma.temp_check_ioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` temp_check_ios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` temp_check_ios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of temp_check_ios.
   */
  distinct?: Prisma.Temp_check_ioScalarFieldEnum | Prisma.Temp_check_ioScalarFieldEnum[]
}

/**
 * temp_check_io findMany
 */
export type temp_check_ioFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * Filter, which temp_check_ios to fetch.
   */
  where?: Prisma.temp_check_ioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of temp_check_ios to fetch.
   */
  orderBy?: Prisma.temp_check_ioOrderByWithRelationInput | Prisma.temp_check_ioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing temp_check_ios.
   */
  cursor?: Prisma.temp_check_ioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` temp_check_ios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` temp_check_ios.
   */
  skip?: number
  distinct?: Prisma.Temp_check_ioScalarFieldEnum | Prisma.Temp_check_ioScalarFieldEnum[]
}

/**
 * temp_check_io create
 */
export type temp_check_ioCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * The data needed to create a temp_check_io.
   */
  data: Prisma.XOR<Prisma.temp_check_ioCreateInput, Prisma.temp_check_ioUncheckedCreateInput>
}

/**
 * temp_check_io createMany
 */
export type temp_check_ioCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many temp_check_ios.
   */
  data: Prisma.temp_check_ioCreateManyInput | Prisma.temp_check_ioCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * temp_check_io update
 */
export type temp_check_ioUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * The data needed to update a temp_check_io.
   */
  data: Prisma.XOR<Prisma.temp_check_ioUpdateInput, Prisma.temp_check_ioUncheckedUpdateInput>
  /**
   * Choose, which temp_check_io to update.
   */
  where: Prisma.temp_check_ioWhereUniqueInput
}

/**
 * temp_check_io updateMany
 */
export type temp_check_ioUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update temp_check_ios.
   */
  data: Prisma.XOR<Prisma.temp_check_ioUpdateManyMutationInput, Prisma.temp_check_ioUncheckedUpdateManyInput>
  /**
   * Filter which temp_check_ios to update
   */
  where?: Prisma.temp_check_ioWhereInput
  /**
   * Limit how many temp_check_ios to update.
   */
  limit?: number
}

/**
 * temp_check_io upsert
 */
export type temp_check_ioUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * The filter to search for the temp_check_io to update in case it exists.
   */
  where: Prisma.temp_check_ioWhereUniqueInput
  /**
   * In case the temp_check_io found by the `where` argument doesn't exist, create a new temp_check_io with this data.
   */
  create: Prisma.XOR<Prisma.temp_check_ioCreateInput, Prisma.temp_check_ioUncheckedCreateInput>
  /**
   * In case the temp_check_io was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.temp_check_ioUpdateInput, Prisma.temp_check_ioUncheckedUpdateInput>
}

/**
 * temp_check_io delete
 */
export type temp_check_ioDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
  /**
   * Filter which temp_check_io to delete.
   */
  where: Prisma.temp_check_ioWhereUniqueInput
}

/**
 * temp_check_io deleteMany
 */
export type temp_check_ioDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which temp_check_ios to delete
   */
  where?: Prisma.temp_check_ioWhereInput
  /**
   * Limit how many temp_check_ios to delete.
   */
  limit?: number
}

/**
 * temp_check_io without action
 */
export type temp_check_ioDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the temp_check_io
   */
  select?: Prisma.temp_check_ioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the temp_check_io
   */
  omit?: Prisma.temp_check_ioOmit<ExtArgs> | null
}
